cat > _config.yml << 'EOF'
title: Alexander Avilez
description: MS ECE student @ Purdue
lang: en
baseurl: ""
url: "https://aavilezb.github.io"
author: Alexander Avilez
markdown: kramdown
permalink: /:year/:month/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

github_username: "aavilezb"

giscus:
  repo: ""
  repo_id: ""
  category: "Announcements"
  category_id: ""

links:
  github: "https://github.com/aavilezb"
  linkedin: "www.linkedin.com/in/alexander-avilez-bah"
  email: "aavilezb@purdue.edu"

goatcounter: ""
EOF
